export interface HotkeyDefinition {
  id: string
  label: string
  description: string
  defaultKey: string
  category: 'global' | 'sessions' | 'session-detail' | 'navigation' | 'selection'
  scope: string | string[]
}

export const HOTKEY_DEFINITIONS: Record<string, HotkeyDefinition> = {
  // Global
  toggleSettings: {
    id: 'toggleSettings',
    label: 'Settings',
    description: 'Open/close settings dialog',
    defaultKey: 'meta+shift+s, ctrl+shift+s',
    category: 'global',
    scope: '.',
  },
  toggleHotkeyPanel: {
    id: 'toggleHotkeyPanel',
    label: 'Keyboard Shortcuts',
    description: 'Show keyboard shortcuts panel',
    defaultKey: '?',
    category: 'global',
    scope: '.',
  },
  openCommandPalette: {
    id: 'openCommandPalette',
    label: 'Command Palette',
    description: 'Open command palette',
    defaultKey: 'meta+k, ctrl+k',
    category: 'global',
    scope: '*',
  },
  createSession: {
    id: 'createSession',
    label: 'New Session',
    description: 'Create a new session',
    defaultKey: 'c',
    category: 'global',
    scope: '.',
  },
  jumpToApproval: {
    id: 'jumpToApproval',
    label: 'Jump to Approval',
    description: 'Navigate to most recent pending approval',
    defaultKey: 'meta+shift+j, ctrl+shift+j',
    category: 'global',
    scope: '.',
  },
  openFeedback: {
    id: 'openFeedback',
    label: 'Submit Feedback',
    description: 'Open feedback form',
    defaultKey: 'meta+shift+f, ctrl+shift+f',
    category: 'global',
    scope: '*',
  },

  // Navigation
  goToSessions: {
    id: 'goToSessions',
    label: 'Go to Sessions',
    description: 'Navigate to sessions list',
    defaultKey: 'g>s',
    category: 'navigation',
    scope: '.',
  },
  goToArchived: {
    id: 'goToArchived',
    label: 'Go to Archived',
    description: 'Navigate to archived sessions',
    defaultKey: 'g>e',
    category: 'navigation',
    scope: '.',
  },
  goToInbox: {
    id: 'goToInbox',
    label: 'Go to Inbox',
    description: 'Navigate to inbox (sessions)',
    defaultKey: 'g>i',
    category: 'navigation',
    scope: '.',
  },
  goToDrafts: {
    id: 'goToDrafts',
    label: 'Go to Drafts',
    description: 'Navigate to drafts view',
    defaultKey: 'g>d',
    category: 'navigation',
    scope: '.',
  },

  // Session List
  navigateDown: {
    id: 'navigateDown',
    label: 'Navigate Down',
    description: 'Move focus to next session',
    defaultKey: 'j, ArrowDown',
    category: 'sessions',
    scope: 'sessions',
  },
  navigateUp: {
    id: 'navigateUp',
    label: 'Navigate Up',
    description: 'Move focus to previous session',
    defaultKey: 'k, ArrowUp',
    category: 'sessions',
    scope: 'sessions',
  },
  jumpToTop: {
    id: 'jumpToTop',
    label: 'Jump to Top',
    description: 'Jump to first session',
    defaultKey: 'g>g',
    category: 'sessions',
    scope: 'sessions',
  },
  jumpToBottom: {
    id: 'jumpToBottom',
    label: 'Jump to Bottom',
    description: 'Jump to last session',
    defaultKey: 'shift+g',
    category: 'sessions',
    scope: 'sessions',
  },
  openSession: {
    id: 'openSession',
    label: 'Open Session',
    description: 'Open the focused session',
    defaultKey: 'Enter',
    category: 'sessions',
    scope: 'sessions',
  },
  toggleSelection: {
    id: 'toggleSelection',
    label: 'Toggle Selection',
    description: 'Select/deselect focused session',
    defaultKey: 'x',
    category: 'selection',
    scope: 'sessions',
  },
  extendSelectionDown: {
    id: 'extendSelectionDown',
    label: 'Extend Selection Down',
    description: 'Add next session to selection',
    defaultKey: 'shift+j, shift+ArrowDown',
    category: 'selection',
    scope: 'sessions',
  },
  extendSelectionUp: {
    id: 'extendSelectionUp',
    label: 'Extend Selection Up',
    description: 'Add previous session to selection',
    defaultKey: 'shift+k, shift+ArrowUp',
    category: 'selection',
    scope: 'sessions',
  },
  selectAll: {
    id: 'selectAll',
    label: 'Select All',
    description: 'Select all sessions',
    defaultKey: 'meta+a, ctrl+a',
    category: 'selection',
    scope: 'sessions',
  },
  clearSelection: {
    id: 'clearSelection',
    label: 'Clear Selection',
    description: 'Deselect all sessions',
    defaultKey: 'Escape',
    category: 'selection',
    scope: 'sessions',
  },
  archiveSession: {
    id: 'archiveSession',
    label: 'Archive/Unarchive',
    description: 'Archive or unarchive selected sessions',
    defaultKey: 'e',
    category: 'sessions',
    scope: 'sessions',
  },
  deleteSession: {
    id: 'deleteSession',
    label: 'Delete Session',
    description: 'Permanently delete selected sessions',
    defaultKey: 'meta+backspace, shift+backspace',
    category: 'sessions',
    scope: 'sessions',
  },
  renameSession: {
    id: 'renameSession',
    label: 'Rename Session',
    description: 'Rename the focused session',
    defaultKey: 'shift+r',
    category: 'sessions',
    scope: 'sessions',
  },
  toggleArchivedView: {
    id: 'toggleArchivedView',
    label: 'Toggle View',
    description: 'Toggle between normal and archived view',
    defaultKey: 'Tab',
    category: 'sessions',
    scope: 'sessions',
  },

  // Session Detail
  closeDetail: {
    id: 'closeDetail',
    label: 'Close Detail',
    description: 'Close session detail view',
    defaultKey: 'Escape',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  nextEvent: {
    id: 'nextEvent',
    label: 'Next Event',
    description: 'Navigate to next event',
    defaultKey: 'j',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  previousEvent: {
    id: 'previousEvent',
    label: 'Previous Event',
    description: 'Navigate to previous event',
    defaultKey: 'k',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  scrollToTop: {
    id: 'scrollToTop',
    label: 'Scroll to Top',
    description: 'Scroll to top of conversation',
    defaultKey: 'g>g',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  scrollToBottom: {
    id: 'scrollToBottom',
    label: 'Scroll to Bottom',
    description: 'Scroll to bottom of conversation',
    defaultKey: 'shift+g',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  jumpToLastUserMessage: {
    id: 'jumpToLastUserMessage',
    label: 'Last User Message',
    description: 'Jump to last user message',
    defaultKey: 'u',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  inspectTool: {
    id: 'inspectTool',
    label: 'Inspect Tool',
    description: 'Inspect tool/sub-agent details',
    defaultKey: 'i',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  toggleSubAgentGroup: {
    id: 'toggleSubAgentGroup',
    label: 'Toggle Sub-agent',
    description: 'Expand/collapse sub-agent group',
    defaultKey: 'h',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  collapseTaskGroup: {
    id: 'collapseTaskGroup',
    label: 'Collapse Task',
    description: 'Collapse task group',
    defaultKey: 'l',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  approve: {
    id: 'approve',
    label: 'Approve',
    description: 'Approve pending action',
    defaultKey: 'a',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  deny: {
    id: 'deny',
    label: 'Deny',
    description: 'Deny pending action',
    defaultKey: 'd',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  archiveDetailSession: {
    id: 'archiveDetailSession',
    label: 'Archive Session',
    description: 'Archive current session',
    defaultKey: 'e',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  renameDetailSession: {
    id: 'renameDetailSession',
    label: 'Rename Session',
    description: 'Rename current session',
    defaultKey: 'shift+r',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  changeModel: {
    id: 'changeModel',
    label: 'Change Model',
    description: 'Change session model',
    defaultKey: 'shift+m',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  interruptSession: {
    id: 'interruptSession',
    label: 'Interrupt Session',
    description: 'Interrupt running session',
    defaultKey: 'ctrl+x',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  goToParent: {
    id: 'goToParent',
    label: 'Parent Session',
    description: 'Go to parent session',
    defaultKey: 'p',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  toggleForkView: {
    id: 'toggleForkView',
    label: 'Toggle Fork View',
    description: 'Toggle fork view',
    defaultKey: 'meta+y, ctrl+y',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  toggleAutoAcceptEdits: {
    id: 'toggleAutoAcceptEdits',
    label: 'Auto-accept Edits',
    description: 'Toggle auto-accept edits',
    defaultKey: 'alt+a, option+a',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  toggleBypassPermissions: {
    id: 'toggleBypassPermissions',
    label: 'Bypass Permissions',
    description: 'Toggle bypass permissions',
    defaultKey: 'alt+y, option+y',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  focusInput: {
    id: 'focusInput',
    label: 'Focus Input',
    description: 'Focus response input',
    defaultKey: 'Enter',
    category: 'session-detail',
    scope: 'sessions.details',
  },
  submitResponse: {
    id: 'submitResponse',
    label: 'Submit Response',
    description: 'Submit response',
    defaultKey: 'meta+enter, ctrl+enter',
    category: 'session-detail',
    scope: 'sessions.details',
  },
}

export type HotkeyId = keyof typeof HOTKEY_DEFINITIONS

// Helper to get default bindings as a record
export function getDefaultBindings(): Record<HotkeyId, string> {
  return Object.fromEntries(
    Object.entries(HOTKEY_DEFINITIONS).map(([id, def]) => [id, def.defaultKey]),
  ) as Record<HotkeyId, string>
}

// Category labels for display
export const HOTKEY_CATEGORY_LABELS: Record<HotkeyDefinition['category'], string> = {
  global: 'Global',
  navigation: 'Navigation',
  sessions: 'Session List',
  selection: 'Selection',
  'session-detail': 'Session Detail',
}
