// Code generated by MockGen. DO NOT EDIT.
// Source: question/types.go
//
// Generated by this command:
//
//	mockgen -source=question/types.go -destination=question/mock_question.go -package=question Manager
//

// Package question is a generated GoMock package.
package question

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	store "github.com/humanlayer/humanlayer/hld/store"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AnswerQuestion mocks base method.
func (m *MockManager) AnswerQuestion(ctx context.Context, id string, answersJSON json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerQuestion", ctx, id, answersJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerQuestion indicates an expected call of AnswerQuestion.
func (mr *MockManagerMockRecorder) AnswerQuestion(ctx, id, answersJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerQuestion", reflect.TypeOf((*MockManager)(nil).AnswerQuestion), ctx, id, answersJSON)
}

// CreateQuestion mocks base method.
func (m *MockManager) CreateQuestion(ctx context.Context, sessionID string, questionsJSON json.RawMessage) (*store.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", ctx, sessionID, questionsJSON)
	ret0, _ := ret[0].(*store.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockManagerMockRecorder) CreateQuestion(ctx, sessionID, questionsJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockManager)(nil).CreateQuestion), ctx, sessionID, questionsJSON)
}

// DeclineQuestion mocks base method.
func (m *MockManager) DeclineQuestion(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineQuestion indicates an expected call of DeclineQuestion.
func (mr *MockManagerMockRecorder) DeclineQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineQuestion", reflect.TypeOf((*MockManager)(nil).DeclineQuestion), ctx, id)
}

// GetPendingQuestions mocks base method.
func (m *MockManager) GetPendingQuestions(ctx context.Context, sessionID string) ([]*store.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingQuestions", ctx, sessionID)
	ret0, _ := ret[0].([]*store.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingQuestions indicates an expected call of GetPendingQuestions.
func (mr *MockManagerMockRecorder) GetPendingQuestions(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingQuestions", reflect.TypeOf((*MockManager)(nil).GetPendingQuestions), ctx, sessionID)
}

// GetQuestionsBySession mocks base method.
func (m *MockManager) GetQuestionsBySession(ctx context.Context, sessionID string) ([]*store.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsBySession", ctx, sessionID)
	ret0, _ := ret[0].([]*store.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsBySession indicates an expected call of GetQuestionsBySession.
func (mr *MockManagerMockRecorder) GetQuestionsBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsBySession", reflect.TypeOf((*MockManager)(nil).GetQuestionsBySession), ctx, sessionID)
}

// GetQuestion mocks base method.
func (m *MockManager) GetQuestion(ctx context.Context, id string) (*store.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestion", ctx, id)
	ret0, _ := ret[0].(*store.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestion indicates an expected call of GetQuestion.
func (mr *MockManagerMockRecorder) GetQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestion", reflect.TypeOf((*MockManager)(nil).GetQuestion), ctx, id)
}
