export const HOTKEY_SCOPES = {
  GLOBAL: '*',
  ROOT: '.',
  SESSIONS: 'sessions',
  SESSIONS_ARCHIVED: 'sessions.archived',
  SESSIONS_BYPASS_PERMISSIONS_MODAL: 'sessions.bypassPermissionsModal',
  SESSION_DETAIL: 'sessions.details',
  SESSION_DETAIL_ARCHIVED: 'sessions.details.archived',
  SESSION_DETAIL_DRAFT: 'sessions.details.draft',
  DRAFT_LAUNCHER: 'sessions.details.draftLauncher',
  SESSION_DETAIL_FORK_IN_PROGRESS: 'sessions.details.forkInProgress',
  FORK_MODAL: 'sessions.details.forkModal',
  TOOL_RESULT_MODAL: 'sessions.details.toolResultModal',
  BYPASS_PERMISSIONS_MODAL: 'sessions.details.bypassPermissionsModal',
  SELECT_MODEL_MODAL: 'sessions.details.selectModelModal',
  DISCARD_DRAFT_DIALOG: 'sessions.details.discardDraftDialog',
  THEME_SELECTOR: 'themeSelector',
  KEYBOARD_HELPER: 'keyboardHelper',
  SETTINGS_MODAL: 'settingsModal',
  TITLE_EDITING: 'sessions.details.titleEditing',
  ADDITIONAL_DIRECTORIES: 'additionalDirectories',
  SESSION_LAUNCHER: 'sessions.launcher',
  TELEMETRY_MODAL: 'telemetry-modal',
} as const

export type HotkeyScope = (typeof HOTKEY_SCOPES)[keyof typeof HOTKEY_SCOPES]
